### PR TITLE
Add Dutch (nl_NL) job titles

### PR DESCRIPTION
**Pull request by SjorsO**
This PR adds dutch job titles. I took them from [this Wikipedia page](https://nl.wikipedia.org/wiki/Lijst_van_beroepen).

The Wikipedia list had some job titles that ended in text between parentheses, this was usually either a female alternative (e.g.: `Acteur (Actrice)`), or a clarification (e.g.: `Analist (laboratorium)`). I've removed all the text between parentheses.

### CODE REVIEW

**Comment by fzaninotto** [comment]
Please add a formatter and some documentation in the locale-specific section of the documentation.

**Comment by SjorsO** [comment]
@fzaninotto Done, let me know if there is anything else

**Comment by pimjansen** [comment]
Nice addition! Looks good to me

**Comment by fzaninotto** [comment]
thanks!

**Pull request merged**
