### PR TITLE
add Algerian (ar_DZ) names provider

### PR DESCRIPTION
**Pull request by djug**

### CODE REVIEW

**Comment by fzaninotto** [comment]
The code formatting check failed, please see Travis report.

**Comment by djug** [comment]
Hi @fzaninotto 
I fixed the indentation in one line that was causing the code formatting check to fail , but Travis test is still failing (my local PHPCS doesn't return any errors)
would you please tell me where I should look, or what I should fix?
thanks

**Comment by cherifGsoul** [comment]
Many thanks for this @djug

**Comment by fzaninotto** [comment]
> PHP Parse error:  syntax error, unexpected '[' in /home/travis/build/fzaninotto/Faker/src/Faker/Provider/ar_DZ/Person.php on line 7

**Comment by fzaninotto** [comment]
Bump, can you fix the syntax?

**Comment by FooBarQuaxx** [comment]
Use the **array()** notation instead of [].

**Comment by djug** [comment]
@FooBarQuaxx I did,
but all check still fail

**Comment by okj579** [comment]
Your test is failing 
> There was 1 failure:
> 
> 1) Faker\Test\Provider\ProviderOverrideTest::testPerson with data set #0 ('ar_DZ')
> 
> Failed asserting that '' matches PCRE pattern "/.+/u".
> 
> /home/travis/build/fzaninotto/Faker/test/Faker/Provider/ProviderOverrideTest.php:100

**Comment by fzaninotto** [comment]
No news  for a long time, closing.

**Comment by FooBarQuaxx** [comment]
@fzaninotto: I have fixed the issue on this pull request #1099.

**Pull request closed without merging**
