### PR TITLE
Update Address.php

### PR DESCRIPTION
**Pull request by Saibamen**
Correct names. Cities cannot have commas.

False city names in this file was from wrong Wikipedia links like:
`[[Lutherstadt Wittenberg|Wittenberg, Lutherstadt]]`

Correct names:
https://de.wikipedia.org/wiki/Lutherstadt_Eisleben
https://de.wikipedia.org/wiki/Lutherstadt_Wittenberg

### CODE REVIEW

**Comment by ppelgrims** [comment]
The problem which caused the tests to fail is fixed. You can build again by closing and reopening this PR, rebasing and pushing, or by empty committing to this branch.

**Comment by Saibamen** [comment]
@ppelgrims Done

**Comment by fzaninotto** [comment]
The problem is that now the cities are in the wrong alphabetical order. But it's better to leave them like that, for seeded generated lists.

**Comment by fzaninotto** [comment]
Thanks

**Pull request merged**
