### PR TITLE
Replaces rtrim with preg_replace

### PR DESCRIPTION
**Pull request by ppelgrims**
As discussed in #1378, tests were added as well

### CODE REVIEW

**Comment by akalongman** [comment]
@fzaninotto when it can be merged?

**Comment by fzaninotto** [comment]
Thanks!

**Comment by tifabien** [comment]
@fzaninotto Do you have any ETA for a new release including this fix? Thanks!

**Comment by ppelgrims** [comment]
@tifabien see #1391

**Comment by tifabien** [comment]
Thanks I'll try it!

**Pull request merged**
