### PR TITLE
Enhancement: Update vimeo/psalm

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] updates `vimeo/psalm`
* [x] regenerates the baseline

💁‍♂️ For reference, see https://github.com/vimeo/psalm/releases/tag/3.18.2.

### CODE REVIEW

**Comment by localheinz** [comment]
@pimjansen @fzaninotto 

Rebased!

**Comment by pimjansen** [comment]
@localheinz still got some conflicts on the baseline it seems

**Comment by localheinz** [comment]
@pimjansen 

Rebased!

**Review by pimjansen — APPROVED** [review]

**Comment by localheinz** [comment]
Thank you, @pimjansen!

**Pull request merged**
