### PR TITLE
Update UserAgent.php

### PR DESCRIPTION
**Pull request by ajbdev**
Updating random user agent strings to appear more modern

I based my changes off a recent log file on a relatively active website I help maintain

### CODE REVIEW

**Comment by ajbdev** [comment]
I am aware that the contributers file reads: "Avoid changing existing sets of data. Some developers use Faker with seeding for unit tests ; changing the data makes their tests fail."

However, the UserAgent provider is a bit unique, as realistic fake data evolves much quicker than the other providers. I'm running into a use case where I am using faker to generate a fake user agent for a scraper. Given the current state of Faker it will create a pattern of outdated browsers, which is undesirable for a scraping tool.

**Comment by fzaninotto** [comment]
Does that mean we'll have to update this provider each time a browser vendor bumps their version? I don't think it makes sense.

I agree with you that the current useragents are outdated, but Faker doesn't mean to be exhaustive, it means to be random. 

I wonder what other users feel about this?

**Comment by ajbdev** [comment]
Yeah, I can certainly understand that point of view - there's no way I would want to maintain this so frequently. Really I just did the PR to cover my specific use case, if it's a no-go I understand I'll just use my fork. 

If the data was just a year or two old it would have been fine for my use case, but it was pretty far outdated. If it's ever been considered to update it, here's an opportunity with most of the work already done. 

I'll be in the same spot again in 2-3 years, but I'm comfortable saying that I'd maintain a frequency at that rate :)

**Comment by fzaninotto** [comment]
Thanks!

**Comment by bomjastik** [comment]
Hi @ajbdev. 

Just decided to use this functionality for a random user-agent generation too. 

I can't find a more specific solution/api.

> I'll be in the same spot again in 2-3 years.

The time is definitely have come :)

Will, you able to update this again?

Regards!

**Pull request merged**
