### PR TITLE
Real Dutch postal codes

### PR DESCRIPTION
**Pull request by ametad**
The included postal codes are randomly taken from a database with real Dutch codes.

### CODE REVIEW

**Comment by fzaninotto** [comment]
No thanks, I prefer a generator.

**Comment by ametad** [comment]
Hello fzaninotto,

What has changed? I saw a similar PR for the Belgian postal codes that you accepted: https://github.com/fzaninotto/Faker/pull/1004

In our tests we also need real existing codes and I would be very grateful if this could be implemented in your Faker lib.

**Comment by fzaninotto** [comment]
in #1004, I understood that these were the only postal codes in Belgium (my mistake?), so there was no need for more randomness. From your PR, I understand that you're including only a subset of the possible post codes. So in effect, you're reducing the possible values of the Dutch post codes.

If some of the generated post codes aren't valid, maybe you can update the formatter to match a certain format?

**Comment by ametad** [comment]
Thank you for your explanation.

There are a lot more postal codes in Belgium! And indeed my PR is also a subset of all the postal codes in the Netherlands. 

The thing is; I need codes that are really in use. And this is not something that can be calculated. Although the format "%### ??" is correct, not all possible outcome is (already) in use today, but could be in use tomorrow if a new part of a city is build (suburb with some streets). You see, in the Netherlands every street part (even side, uneven side, high number, low numbers) has it own postal code! So in the same street the houses can have two, three, more, different postal codes.

For my tests, I need postal codes that are in use today. Because it is compared with an external services, so that input forms only accept existing codes (validation) and therefore are real addresses. 

Will you accept my PR?

**Comment by ametad** [comment]
I could expand the list to (say) double the codes, so there is more randomness.

**Comment by fzaninotto** [comment]
OK, I'll reopen this. Please triple the list size.

**Comment by ametad** [comment]
Will do triple the size and check back when ready. Thank you.

**Comment by ametad** [comment]
Tests are green :)

**Comment by fzaninotto** [comment]
Thanks!

**Pull request merged**
