### PR TITLE
Add ar_SA Color Provider

### PR DESCRIPTION
**Pull request by alhoqbani**

### CODE REVIEW

**Comment by fzaninotto** [comment]
Could you go a bit further and provide a list of all color names?

**Comment by alhoqbani** [comment]
I got the list of colors from Wikipedia, but it's a long list. 
Let me know if you want me to change it. 

https://ar.wikipedia.org/wiki/%D9%82%D8%A7%D8%A6%D9%85%D8%A9_%D8%A7%D9%84%D8%A3%D9%84%D9%88%D8%A7%D9%86_(%D9%85%D8%AA%D8%B6%D8%A7%D9%85%D8%A9)

**Comment by fzaninotto** [comment]
That's fine. It'd be even better if you added a comment linking to the Wikipedia page in the source.

**Comment by fzaninotto** [comment]
Great, thanks!

**Pull request merged**
