### PR TITLE
Update pt_BR names

### PR DESCRIPTION
**Pull request by thiagotalma**
Change Hispanic names by genuinely Brazilian names.
( because Brazil is a Latin country, but it is not Hispanic, it is Portuguese 😉 )

### CODE REVIEW

**Comment by fzaninotto** [comment]
Please find an external datasource for these arrays, with an open-source licence. Otherwise every dev in the world can say they have better data and I have no way to tell which one is right.

**Comment by thiagotalma** [comment]
I understand your preoccupation.
However I checked in the change history that there was no major change to this file. No Brazilian native had the job of writing Brazilian names. I am the first to do this.

Why not accept my suggestions and create difficulties for the next PR who try to recreate everything again?

Or you may even have the job of correcting this manually and closing the PR.
Use http://www.fakenamegenerator.com

What can not do is continue to give Hispanic names to Brazilians 😉

**Comment by fzaninotto** [comment]
> Why not accept my suggestions and create difficulties for the next PR who try to recreate everything again?

Because it's not because I made mistakes in the past (by accepting data without a proper source) that I want to continue making more.

**Comment by dknacht** [comment]
Hi, I can guarantee that those name he erased were **Hispanic**, not Brazilian at all.
What type external of source would you accept? I'll try to find one, but while I search for a trusted and open one, I think that the names he wrote, even if are not 100% correct are much better than the ones are being used actually.

**Comment by fzaninotto** [comment]
Any MIT-compatible datasource will fit.

In the meantime, I won't merge this PR. I will close it in a few weeks if there is no update.

**Comment by thiagotalma** [comment]
There is no update I can do, you can close now.

I would gain nothing at all with this, my intention was only to collaborate.

**Pull request closed without merging**
