### PR TITLE
Add a building number with letter to German speaking locales.

### PR DESCRIPTION
**Pull request by markuspoerschke**
In Austria, Germany, and Switzerland a building number can have a letter as a suffix. Example: `Hauptstraße 23a`.

### CODE REVIEW

**Comment by fzaninotto** [comment]
Tests fail

**Comment by markuspoerschke** [comment]
The test is based on fortuity. Changing the test to the following solved the problem:

```
public function testMobilePhoneNumberStartWith9Returns9yxxxxxx()
    {
        $mobileNumber = $this->faker->mobileNumber();
        $mobileNumber = $this->faker->mobileNumber();
        $mobileNumber = $this->faker->mobileNumber();
        $mobileNumber = $this->faker->mobileNumber();
        $mobileNumber = $this->faker->mobileNumber();
        $mobileNumber = $this->faker->mobileNumber();
        $startsWith9 = false;
        while (!$startsWith9) {
            $mobileNumber = $this->faker->mobileNumber();
            $startsWith9 = preg_match('/^(\+65|65)?\s*9/', $mobileNumber);
        }

        $this->assertRegExp('/^(\+65|65)?\s*9\s*[0-8]{3}\s*\d{4}$/', $mobileNumber);
    }
```
I fixed the test by resetting the seed.

**Comment by fzaninotto** [comment]
Thanks!

**Comment by markuspoerschke** [comment]
:-) Thanks for merging!

**Pull request merged**
