### PR TITLE
Created el_GR files for Company address

### PR DESCRIPTION
**Pull request by drakakisgeo**
Made some minor changes to the address file and created the company file for el_GR language.

### CODE REVIEW

**Comment by ronanguilloux** [comment]
Hi @lollypopgr,

Thanks for your attempt to contribute to Faker! The Travis-CI continuous server answered to your commit with some litlle warnings: **Not a big deal to fix* ;-). This automatic check allows this project to remain stable & nice.

Just use the  `make sniff test` command in a terminal, in your Faker project root folder, in order to have a review for your contribution style & non-regression. The command will respond you with some improvements to make this project stable & nice:

```
FILE: ...Faker/src/Faker/Provider/el_GR/Company.php
--------------------------------------------------------------------------------
FOUND 5 ERROR(S) AFFECTING 5 LINE(S)
--------------------------------------------------------------------------------
  4 | ERROR | Line indented incorrectly; expected 0 spaces, found 1
  5 | ERROR | Expected 0 spaces before opening brace; 1 found
 50 | ERROR | Line indented incorrectly; expected at least 8 spaces, found 5
 59 | ERROR | Line indented incorrectly; expected at least 8 spaces, found 5
 63 | ERROR | The closing brace for the class must go on the next line after the body
--------------------------------------------------------------------------------
UPGRADE TO PHP_CODESNIFFER 2.0 TO FIX ERRORS AUTOMATICALLY
--------------------------------------------------------------------------------
```

Have a look at [PSR2](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md) Standard Style to understand how to fix these unwanted spaces & bad closing braces positions.

We're looking forward to review your next commit ;-)

**Comment by fzaninotto** [comment]
Bump. Please fix the CS issues or I won't be able to merge this PR.

**Comment by drakakisgeo** [comment]
Corrected this @fzaninotto . Sorry for the waiting.

**Comment by fzaninotto** [comment]
Thanks!

**Pull request merged**
