### PR TITLE
Fix ng_NG to en_NG

### PR DESCRIPTION
**Pull request by raphaeldealmeida**
Localization for Nigeria should be en_NG #1171 Renamed classes and created a readme entry

### CODE REVIEW

**Comment by fzaninotto** [comment]
There are conflicts, can you rebase?

**Comment by raphaeldealmeida** [comment]
Its done :+1:

**Comment by fzaninotto** [comment]
bad rebase: there are changes in your PR unrelated to this PR. Please rebase again.

**Comment by raphaeldealmeida** [comment]
I can't rebase correctly. I'll close this and open another PR

**Pull request closed without merging**
