### PR TITLE
Adding it_IT Text Provider

### PR DESCRIPTION
**Pull request by endelwar**
Added Dante Alighieri's Inferno to the italian text provider

### CODE REVIEW

**Comment by fzaninotto** [comment]
I think a more modern text in prose would produce better results...

**Comment by endelwar** [comment]
What about Pinocchio by Collodi?

**Comment by fzaninotto** [comment]
Better idea !

**Comment by davelopware** [comment]
By total coincidence, I've just done the Dante's Inferno Text.php file myself too, and came here to offer it as a pull :)

**Comment by endelwar** [comment]
I forgot to report here that the text was updated @fzaninotto

**Comment by fzaninotto** [comment]
Thanks!

**Pull request merged**
