### PR TITLE
Add lorem files, modify data, change the format

### PR DESCRIPTION
**Pull request by AmiBang**
Why before inspections department through?Submit this time?

### CODE REVIEW

**Comment by AmiBang** [comment]
Compiled automatically checks strictly, really helpless

**Comment by fzaninotto** [comment]
Lorem is never localized ; don't add one or two elements in a data set. Instead, replace the entire dataset, but reference an external (and open-source) dataset.

**Comment by AmiBang** [comment]
Have changed, thank you for your prompt.Really want to do some contribution!

**Comment by AmiBang** [comment]
Thank you, very clear tell my mistake, I will carefully read contributors guide. I will also continue to contribute.

**Pull request closed without merging**
