### PR TITLE
Fix "Resource temporarily unavailable" when cURL fails due to SSL ver…

### PR DESCRIPTION
**Pull request by fatonsopa**
Fix "Resource temporarily unavailable" when cURL fails due to SSL verification

### CODE REVIEW

**Comment by jcqtc** [comment]
Works well with me thanks! 👍 Just need an extra space line 91 so the build can pass without any error.

**Comment by fatonsopa** [comment]
Hey @jcqtc, glad it helped you. 
I'm not finding details about where the check is failing. Can you send me a URL or screenshot of where it is failing?

**Comment by jcqtc** [comment]
Here's the link: https://travis-ci.org/fzaninotto/Faker/jobs/384760428.

At line 208 & 209 of the log (didn't see the second error):

```
--------------------------------------------------------------------------------
FOUND 2 ERROR(S) AFFECTING 2 LINE(S)
--------------------------------------------------------------------------------
  91 | ERROR | Expected "} elseif (...) {\n"; found "} elseif(...) {\n"
 104 | ERROR | Expected "if (...) {\n"; found "if(...){\n"
--------------------------------------------------------------------------------
```

**Comment by fatonsopa** [comment]
<pre>
<code>

LoremPixel is offline, skipping image download
/home/travis/build/fzaninotto/Faker/test/Faker/Provider/ImageTest.php:59
ERRORS!
Tests: 2005, Assertions: 6677, Errors: 1, Skipped: 1.
make: *** [test] Error 2
</code>
</pre>

**Comment by jcqtc** [comment]
#1484 should fix that!

But I can see another error (line 248 of the [travis log](https://travis-ci.org/fzaninotto/Faker/jobs/384802572)), it has nothing to do with Images so it's a bit weird.

```
1) Faker\Test\Provider\DateTimeTest::testFixedSeedWithMaximumTimestamp
InvalidArgumentException: Start date must be anterior to end date.

/home/travis/build/fzaninotto/Faker/src/Faker/Provider/DateTime.php:134
/home/travis/build/fzaninotto/Faker/src/Faker/Provider/DateTime.php:216
/home/travis/build/fzaninotto/Faker/test/Faker/Provider/DateTimeTest.php:251
```

It's the `dateTimeBetween` function of the [DateTime.php](https://github.com/fzaninotto/Faker/blob/master/src/Faker/Provider/DateTime.php) file that throw an exception because the start date isn't anterior to the end date. Maybe it's because the two dates are actualy the same (don't know if it's possible), if this is true **maybe** changing the `>` operator to `>=` of the line below should fix it.

```
if ($startTimestamp > $endTimestamp) {
    throw new \InvalidArgumentException('Start date must be anterior to end date.');
}
```

**Comment by fatonsopa** [comment]
Strange! It's working on my side. The operator seems fine to me, as long as it checks the anterior date! It looks like the method dateTimeInInterval has somehow received a date that happened to be later than the end date!

**Pull request closed without merging**
