### PR TITLE
Fix spelling errors

### PR DESCRIPTION
**Pull request by driade**

### CODE REVIEW

**Comment by driade** [comment]
Would propose to check if accepted the file. It contains text in other languages, such as Catalonian. As this is es_ES I don't know this texts should be removed to use just Spanish Castilian.

**Comment by fzaninotto** [comment]
I think it's good as is, since street names can be in Catalonian in Catalonia, which is in Spain.

**Comment by driade** [comment]
Not completely agree, sorry. The docs state that the argument passed is the locale, not the country. The Catalonian language has its own locale.

**Comment by driade** [comment]
Also, please, check the changes. I didn't remove any text in Catalonian, just spelling errors.

**Pull request merged**
