### PR TITLE
Prepare 1.5 release

### PR DESCRIPTION
**Pull request by fzaninotto**
- [x] Document more than 100 merged PRs in Changelog
- [ ] Update `composer.json`
- [ ] Tag release in Git
- [ ] Update the Release section in GitHub
- [ ] Write a blog post about the changes
- ??????
- [ ] Profit

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
> Update composer.json

What needs to happen there?

**Comment by fzaninotto** [comment]
Update the line

```
        "branch-alias": {
            "dev-master": "1.5.x-dev"
```

**Comment by GrahamCampbell** [comment]
Why does that need updating? Are you already sure you're not going to do a 1.5.1 release at any point?

**Comment by fzaninotto** [comment]
I'm not sure, but I probably won't.

**Pull request merged**
