### PR TITLE
Added new biasedElementBetween

### PR DESCRIPTION
**Pull request by axettone**
I needed such a method because I had to seed a database with entries having a certain flag equal to "false" only in a small %.
So you can achieve this with:

`$entry->field = $faker->biasedElementBetween([true,false],[0.9,0.1]);`

### CODE REVIEW

**Comment by axettone** [comment]
I renamed the method biasedElementIn (it's more appropriate)

**Comment by fzaninotto** [comment]
Thanks, but I'll pass on this one. Otherwise, what prevents us from re-implementing every formatter in a biaised way? 

I think a better approach would be to inject a custom randomizer in the base object. That would help biaising all formatters at will.

**Comment by axettone** [comment]
Yes, I agree with you. Do you mean we can add an extra-parameter to any method of the Base class so to trigger this thing?

**Comment by fzaninotto** [comment]
No, I was rather thinking about a constructor parameter

**Pull request closed without merging**
