### PR TITLE
added Twitter Handler to Internet Provider

### PR DESCRIPTION
**Pull request by j0an**

### CODE REVIEW

**Comment by fzaninotto** [comment]
All that for an `@`... I think this doesn't bring much value. Faker users will prefer concatenating the `'@'` themselves instead of learning another formatter.

Thanks for your suggestion anyway.

**Comment by GrahamCampbell** [comment]
Same. This would have been really useful.

**Comment by fzaninotto** [comment]
@GrahamCampbell Not sure I get your point. You think a twitter handler formatter would be useful or not?

**Comment by GrahamCampbell** [comment]
I think it would have been useful to have, yeh.

**Comment by j0an** [comment]
I thought that it might be useful. I needed and I think that hardcode an @ was just fine, but a specific handler will be better.



j.

**Comment by fzaninotto** [comment]
But then we need a formatter for Google + which adds a "+", and a formatter for Facebook which just returns `username`, and I don't talk about snapchat or Pinterest... It doesn't make sense in my opinion.

**Comment by j0an** [comment]
aha, you have a point.

perhaps separating the *Internet Handlers* and creating a *Social Media
Handlers*?




j.

**Pull request closed without merging**
