### PR TITLE
remove bad phone number from ru_RU PhoneNumber

### PR DESCRIPTION
**Pull request by shatilov**

### CODE REVIEW

**Comment by fzaninotto** [comment]
Can you link to a public resource explaining the formats of the legal phone numbers in the phpDoc?

**Comment by pwsdotru** [comment]
May be this: https://en.wikipedia.org/wiki/Telephone_numbers_in_Russia

**Comment by fzaninotto** [comment]
...in the phpDoc, so future developers understand your code

**Comment by pimjansen** [comment]
@shatilov bump

**Pull request closed without merging**
