### PR TITLE
Added few countries to he_IL Provider file Address.php

### PR DESCRIPTION
**Pull request by Newman101**
Good morning. I added few countries to he_IL provider file Address.php. 

Thank you.

### CODE REVIEW

**Comment by fzaninotto** [comment]
Could you list all countries instead? Currently, this provider has very low value.

**Comment by Newman101** [comment]
Sure, just let me to re-factor the provider a bit. =)

**Comment by yonirom** [comment]
I'm sorry, I just saw this PR now. 
I saw the TODO in the he_IL provider and went on and created a PR (#841).

Also, why does this provider have very low value? From what i've seen only Payment and Text are missing. Payment is relatively new and can be implemented quite easily. Text is a bit more difficult.

**Comment by fzaninotto** [comment]
Superseded by #841

**Pull request closed without merging**
