### PR TITLE
[ci skip]added .gitattributes

### PR DESCRIPTION
**Pull request by lichunqiang**

### CODE REVIEW

**Comment by fzaninotto** [comment]
No, thanks.

**Comment by lichunqiang** [comment]
Hi, can i get your thought to say no?

**Comment by fzaninotto** [comment]
Can you first explain why you propose that change?

**Comment by lichunqiang** [comment]
Ok. 

Now install via composer will download all the files in the vendor, but always like the `test` folder is no mean for the user.

This change can prevent those files to install to user's vendor.

In my case, our deploy system let us to write all the files which should be deploy online, that's a big work, because lot of depends...

**Comment by lichunqiang** [comment]
for example

https://github.com/laravel/framework/blob/5.3/.gitattributes

**Comment by lichunqiang** [comment]
https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes#Exporting-Your-Repository

**Pull request closed without merging**
