### PR TITLE
VAT and National identification number for the fi_FI provider

### PR DESCRIPTION
**Pull request by lasselehtinen**
Second submit for this pull request. Original one was closed.

https://github.com/fzaninotto/Faker/pull/886

### CODE REVIEW

**Comment by oittaa** [comment]
I also added national id numbers in pull request #1053. My implementation has functions and parameters based on previously implemented functions and tests found in other locales. For example https://github.com/fzaninotto/Faker/blob/master/src/Faker/Provider/sv_SE/Person.php

**Comment by fzaninotto** [comment]
needs rebase

**Comment by fzaninotto** [comment]
Still needs rebase

**Comment by lasselehtinen** [comment]
There isn't anything special in this PR compared to #1053 which is already accepted. So I will close this one.

**Pull request closed without merging**
