### PR TITLE
PHP 7.4 compat

### PR DESCRIPTION
**Pull request by trasher**

### CODE REVIEW

**Comment by erikgaal** [comment]
PHP 7.4 compatibility was already added in #1748.

**Comment by trasher** [comment]
Sounds like something has been missed; and there were no travis test for 7.4.

**Comment by erikgaal** [comment]
Oop, good catch. Assumed that `nightly` would be the testing on `7.4`. Could you please elaborate bit further the required and already made changes in the original post?

**Comment by trasher** [comment]
I'm sorry, I do no understand. Current master fails on PHP 7.4 because of brackets syntax accessing arrays; that is what the current PR fix.
Also, nightly on Travis is PHP 8.0.0 (see travis outputs).

**Comment by localheinz** [comment]
@trasher 

Closing, apologies for the delay.

Also see #1748 and #1861.

**Pull request closed without merging**
