### PR TITLE
add generator for nif

### PR DESCRIPTION
**Pull request by jjbier**

### CODE REVIEW

**Comment by fonsecas72** [comment]
Just wanted to say that it seems that the Spanish NIF is generated in the same way as the Portuguese NIF. Maybe we should give it a thought.
The tests are failing because of CS btw.

**Comment by fzaninotto** [comment]
Yep, please fix CS and add a line to the locale-specific section in README

**Comment by fzaninotto** [comment]
Bump. Can you please update your PR according to my comments?

**Comment by fzaninotto** [comment]
No news for too long, closing.

**Pull request closed without merging**
