### PR TITLE
Add ar_SA locale

### PR DESCRIPTION
**Pull request by ibrasho**

### CODE REVIEW

**Comment by fzaninotto** [comment]
Tests fail, can you check?

**Comment by fzaninotto** [comment]
Bump, I will close your PR shortly of you don't fix the tests

**Comment by ibrasho** [comment]
I just updated the entries. This should resolve the issue.

**Comment by fzaninotto** [comment]
Why did you repeat the `realText()` method in the `Text` provider?

**Comment by ibrasho** [comment]
If I don't, won't it default to faking text from the en_US locale?

**Comment by fzaninotto** [comment]
You just need to override the data in the `Text` provider, not the `realText()` method (which is inherited).

**Comment by ibrasho** [comment]
I've updated the PR and also updated the ar_JO Text provider.

**Comment by fzaninotto** [comment]
Thanks!

**Pull request merged**
