### PR TITLE
Fix for 'The first argument to copy() function cannot be a directory'

### PR DESCRIPTION
**Pull request by svrnm**
This is a fix for the issue #539. Directories are excluded using the provided filter.

### CODE REVIEW

**Comment by fzaninotto** [comment]
Thanks for the patch, can you fix coding standards (see build report)?

**Comment by svrnm** [comment]
I fixed it and double checked it with phpspec:-)

**Comment by fzaninotto** [comment]
Thanks!

**Comment by montogeek** [comment]
Thanks!

**Pull request merged**
