### PR TITLE
Latvian first names

### PR DESCRIPTION
**Pull request by veisis**
Better list of Latvian first names.

### CODE REVIEW

**Comment by fzaninotto** [comment]
We need a datasource. Future maintainers like you will wonder where this list comes from and if it requires update.

**Comment by veisis** [comment]
Source: http://vardunozime.lv/ - popular first names in Latvia. And theirs source is The Office of Citizenship and Migration Affairs http://www.pmlp.gov.lv/en/

**Comment by fzaninotto** [comment]
You didn't understand me. We need a datasource in the code. Please read [the contributing guidelines](https://github.com/fzaninotto/Faker/blob/master/CONTRIBUTING.md).

**Comment by fzaninotto** [comment]
Thanks

**Pull request merged**
