### PR TITLE
latin 'a' to cyrillic 'а'

### PR DESCRIPTION
**Pull request by piunChik**
fix another one typo in last name suffix

### CODE REVIEW

**Comment by ulcuber** [comment]
Same error in tests
[error](https://github.com/fzaninotto/Faker/blob/04c47e38dbc68d7261c88446598bbf509d37c77a/test/Faker/Provider/ru_RU/PersonTest.php#L25)
[error](https://github.com/fzaninotto/Faker/blob/04c47e38dbc68d7261c88446598bbf509d37c77a/test/Faker/Provider/ru_RU/PersonTest.php#L30)

**Comment by pimjansen** [comment]
@piunChik tests are failing, please review

**Comment by nnrudakov** [comment]
Correct tests has made in earlier approved PR [1853](https://github.com/fzaninotto/Faker/pull/1853)

**Comment by localheinz** [comment]
Closing in favour of #2056.

**Pull request closed without merging**
