### PR TITLE
Fix: Update squizlabs/php_codesniffer

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] updates `squizlabs/php_codesniffer`
* [x] runs `make fix`
* [x] cherry-picks a commit from #2079 to fix failing tests

💁‍♂️ For reference, see https://github.com/squizlabs/PHP_CodeSniffer/compare/3.5.4...3.5.8.

### CODE REVIEW

**Review by fzaninotto — APPROVED** [review]

**Comment by fzaninotto** [comment]
merging conflict

**Comment by localheinz** [comment]
@fzaninotto 

Rebased!

**Comment by localheinz** [comment]
Test failure is related to https://github.com/fzaninotto/Faker/pull/2076.

**Comment by localheinz** [comment]
Thank you, @fzaninotto!

**Pull request merged**
