### PR TITLE
Updated link to IBAN formats reference

### PR DESCRIPTION
**Pull request by god107**
Old one doesn't work anymore

### CODE REVIEW

**Comment by okj579** [comment]
This is the file it's based on: https://www.swift.com/node/11971
But maybe this URL is more stable: https://www.swift.com/standards/data-standards/iban

**Comment by god107** [comment]
@okj579 right, second link looks more stable. File is changing quite often. Maybe @fzaninotto should comment, i'm ready to change this any time.

**Comment by fzaninotto** [comment]
I agree, let's use the 'standards' link

**Comment by god107** [comment]
@fzaninotto Fixed, ready for merge

**Comment by fzaninotto** [comment]
thanks!

**Pull request merged**
