### PR TITLE
New Feature: Populate objects and arrays based on simple configuration

### PR DESCRIPTION
**Pull request by clabonte**
I have created a new module that you may want to integrate to your project. This feature allow to use a simple JSON configuration file to define how to populate objects and arrays. 

This module can be handy when you are not dealing with an ORM and you need more control than what is available via the Name guesser to leverage the entire set of formats offered by Faker.

I have provided the phpunit tests along with some examples and updated the Readme.md to explain how it works.

### CODE REVIEW

**Comment by fzaninotto** [comment]
Nice work, but I prefer that you make it a standalone Package, which I can link to in the README.

**Comment by clabonte** [comment]
Sounds good. Any idea for a name for this package? Would you be OK with faker-config?

**Comment by fzaninotto** [comment]
Anything that you see fit

**Comment by clabonte** [comment]
Done. I have published my extension under the following repository:
https://github.com/clabonte/faker-config

And added my package to packagist:
https://packagist.org/packages/clabonte/faker-config

Thanks for your help and your excellent work!

**Comment by fzaninotto** [comment]
Feel free to open a PR in Faker to add a link to your package in the README

**Pull request closed without merging**
