### PR TITLE
en_CA unit test folder added

### PR DESCRIPTION
**Pull request by Newman101**
Unit test support added to en_CA Provider, with PhoneNumberTest.php test kit. 

Thank you.

### CODE REVIEW

**Comment by Newman101** [comment]
Looks like the RegEx does not pass test cases without international calling code. I'll need to modify the RegEx a bit to make sure it includes both numbers with and without country dial in codes.

**Comment by fzaninotto** [comment]
Thanks!

**Comment by fzaninotto** [comment]
Tests fail, I'll revert this one.

```
There was 1 failure:

1) Faker\Test\Provider\en_CA\PhoneNumberTest::testPhoneNumberFormat
Failed asserting that '529-411-8627 x175' matches PCRE pattern "/^((([0-9]{1})*[- .(]*([0-9]{3})[- .)]*[0-9]{3}[- .]*[0-9]{4})+)*$/".

/Users/francois/git/Faker/test/Faker/Provider/en_CA/PhoneNumberTest.php:32
```

**Comment by Newman101** [comment]
Interesting, when I did run the tests it actually passed. I'll need to re-check this one. Thanks for notification.

**Comment by fzaninotto** [comment]
I also partially reverted #767 for the same reason (see 0456c4efc8faffe9359cc75b6896bcc92d458ef6)

**Comment by Newman101** [comment]
OK. I need to re-check these commits. As I mentioned, the build passed while committing.

**Pull request merged**
