### PR TITLE
Created provider for cron expressions.

### PR DESCRIPTION
**Pull request by swekaj**
Created provider to produce valid cron expressions, both basic and extended (as indicated by Wikipedia's [format](http://en.wikipedia.org/wiki/Cron#Format) section).

Also provided methods for the individual Cron fields.

### CODE REVIEW

**Comment by fzaninotto** [comment]
Thanks for your contribution. In my opinion, it's a bit too specific for Faker. I suggest you host a standalone provider in your own GitHub account (like I did for [CompanyNameGenerator](https://github.com/fzaninotto/CompanyNameGenerator)), I'll be happy to link to it in the README.

**Comment by swekaj** [comment]
I'm sorry to hear that, but I went ahead and followed your advice and created [swekaj/CronExpressionGenerator](https://github.com/swekaj/CronExpressionGenerator).

**Comment by fzaninotto** [comment]
Thanks, I mentioned it in the README in aca1dacd6188860684fc344880052f7fa94f709a

**Comment by swekaj** [comment]
Thanks!

**Pull request closed without merging**
