### PR TITLE
[pt_BR][Person] Adding brazillian RG and CPF

### PR DESCRIPTION
**Pull request by hussani**
- RG is a brazilian ID card number
- CPF is like a registry of contributors' identification

This PR is a quick fix of #488, initialized by @ianrodrigues.
All credits belong to him.

### CODE REVIEW

**Comment by igorsantos07** [comment]
Is the code working? The samples doesn't seems to reflect the code behaviour - furthermore, that behaviour of passing a string into a provider's method is uncommon across the library.

Finally, considering there's an year-old PR (#545) about brazilian documents and other improvements, maybe we should add the RG to it instead of having two PR on the same matter?

**Comment by hussani** [comment]
@igorsantos07 I just needed a RG and CPF provider and I saw the open PRs, found one and fix.
Your solution is larger, have some details inexistent on this PR (like CNPJ and others) and the code is more organized.
Personally, prefer your solution than this. I would be glad if your code was merged instead that. :+1:

**Comment by igorsantos07** [comment]
You can make a PR to igorsantos07:improved-pt-cherry-picked and I'll merge it. That will include your commit into #545 :)

**Comment by fzaninotto** [comment]
Superseded by #545. Please collaborate with @igorsantos07

**Pull request closed without merging**
