### PR TITLE
Feature : Add dateTimeInInterval Method

### PR DESCRIPTION
**Pull request by nicodmf**
Permit to take a date and add or substract a php recognized interval.

I'm sure this can be usefull, because i write that in one of my alice loader, but not if this can be look as good writed (long in comparison with other pretty date functions) or in your waited tasks list.

So let me know if you want i finish with csfixer, tests, rebase and all or if this is not usefull.

@see http://php.net/manual/fr/dateinterval.createfromdatestring.php
@see http://php.net/manual/fr/datetime.formats.relative.php

@note : edited directly on github for moment

### CODE REVIEW

**Comment by fzaninotto** [comment]
What's the difference with `dateTimeBetween()`? You just pass a date and an interval instead of passing two dates?

**Comment by nicodmf** [comment]
Yes that the idea. 

And i can pass a date from another field with alice and not an exact date.

Exemple :

```yaml

EntityBundle\Entity\HourSheet:
    Hours{1..1000}:
        start: <dateTimeBetweenInterval('-5 days', '+10 days')>
        end: <dateTimeBetweenInterval($start, '+5 hours')>
        validated: 50%? <dateTimeBetweenInterval($end, '+15 days')>
        sended: 50%? <dateTimeBetweenInterval($validated, '+15 days')>
        activity: @OnlyActivity*
        user: @User*
        yard: @Yard*

```

**Comment by fzaninotto** [comment]
Ok, I can understand the requirement. 

To avoid code duplication, please use `dateTimeBetween()` in your code.

Also, please add a reference of the new formatter in the README.

**Comment by nicodmf** [comment]
@fzaninotto Code rebased, tested and the readme is updated. I can make another changes if needed?

**Comment by fzaninotto** [comment]
Thanks!

**Pull request merged**
