### PR TITLE
Adds generators for Norwegian (nb_NO) counties and "kommune", using existing static arrays in the class

### PR DESCRIPTION
**Pull request by jamesinglis**
The static arrays for "countyNames" and "kommuneNames" were already present in the class to seed the random selection groups, there were just not accessor methods to generate a county or a "kommune". This commit just adds in these accessor methods.

### CODE REVIEW

**Comment by fzaninotto** [comment]
please add a related mention in the locale-specific section of the Readme. Also, please rebase to avoid merge commits.

**Comment by fzaninotto** [comment]
bump

**Comment by localheinz** [comment]
@jamesinglis 

Are you still interested in working on this? If so, we could help you get this through!

**Comment by pimjansen** [comment]
Closing this because it got stale. Please feel free to reopen if needed

**Pull request closed without merging**
