### PR TITLE
[BUGFIX] Fix path to autoload.php in phpunit.xml

### PR DESCRIPTION
**Pull request by r3h6**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This actually looks wrong to me.

**Comment by GrahamCampbell** [comment]
We want to be using composer's autoloader.

**Comment by GrahamCampbell** [comment]
The one in src is only there if you want to use this library without composer.

**Comment by r3h6** [comment]
Didn't thought about composer -> forget then this request.

**Pull request closed without merging**
