### PR TITLE
Add setter and getter to config default locale

### PR DESCRIPTION
**Pull request by vluzrmos**

### CODE REVIEW

**Comment by vluzrmos** [comment]
Keeping the constant DEFAULT_LOCALE to compatibility

**Comment by vluzrmos** [comment]
The methods could be called setLocale and getLocale, whatever. I think, setDefaultLocale and getDefaultLocale is better.

**Comment by fzaninotto** [comment]
What's the use case for that? I fail to see any interest.

**Comment by vluzrmos** [comment]
I've tried to do that on laravel core, but was rejected, I thinking in cases of you can define the default faker locale.

**Comment by fzaninotto** [comment]
You can't define the default Faker locale. You can define the locale you want to use for a given set of fake data.

**Pull request closed without merging**
