### PR TITLE
Enhancement: Run builds on master using GitHub Actions

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] runs builds on `master` using GitHub Actions

💁‍♂ With https://github.com/shivammathur/setup-php/releases/tag/2.0.0 we have support for running PHP 5.3, PHP 5.4, and PHP 5.5 on GitHub Actions.

### CODE REVIEW

**Comment by pimjansen** [comment]
@localheinz i see it is still waiting for a travis build is that correct? Or can that be ignored

**Comment by localheinz** [comment]
@pimjansen 

I think that needs to be removed from the branch protection settings.

@fzaninotto 

Can you take a look, please?

**Comment by fzaninotto** [comment]
Thanks!

**Comment by localheinz** [comment]
Thank you, @fzaninotto and @pimjansen!

**Pull request merged**
