### PR TITLE
Update PhoneNumber.php

### PR DESCRIPTION
**Pull request by nickwebcouk**
Added new number formats for 4 digit area code locations (Glasgow, Edinburgh etc).

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Why all the whitespace changes?

**Comment by nickwebcouk** [comment]
I cancelled #720 and submitted #721. Formatting error on my part. Sorry!

**Comment by GrahamCampbell** [comment]
Please close this then. ;)

**Comment by nickwebcouk** [comment]
closing - replaced with #721

**Pull request closed without merging**
