### PR TITLE
Added Lots of Nepali Male and Female Name.

### PR DESCRIPTION
**Pull request by bravegurkha**
I've added Nepali names. Just found this data somewhere. I thought it would be great to push it on Faker.

### CODE REVIEW

**Comment by Newman101** [comment]
Hi. Looks like there is some white space in your commit. Please remove it. Thank you.

**Comment by fzaninotto** [comment]
"Just found this data somewhere" isn"t compatible with our MIT license.

**Comment by bravegurkha** [comment]
Now it not just the " found somewhere" . I've successfully found the link where I got the data
https://github.com/studenton/gender-data/blob/master/genders.csv

**Comment by fzaninotto** [comment]
hm, this repo claims the data is MIT, but doesn't bundle the license of its sources, so it's doutbful. Besides, one of the sources is GPL V2, not compatible with MIT.

**Comment by bravegurkha** [comment]
Alright. Thank you. I didn't know about the License matters that hardly. I just wanted to contribute to Faker because Faker is helping me a lot. Just wanted to give it back. 😄

**Pull request closed without merging**
