### PR TITLE
change PHPUnit namespace, set coverage setting

### PR DESCRIPTION
**Pull request by peter279k**
As title.

### CODE REVIEW

**Comment by pimjansen** [comment]
@peter279k is this still required? Since we did some changes to the CI pipeline recently already.

**Comment by peter279k** [comment]
Hi @pimjansen, thanks for your reply.

After looking at the [.travis.yml](https://github.com/fzaninotto/Faker/blob/master/.travis.yml) setting on master, it seems that we don't have to let all PHP versions be `precise` dist.

I think we can consider using the `matrix` setting (it's like my approach on this PR) to dispatch different dist for different PHP versions.

**Comment by pimjansen** [comment]
@peter279k i dont really see a problem why they cant all be at precise though?

**Comment by peter279k** [comment]
> @peter279k i dont really see a problem why they cant all be at precise though?

As far as I know, the pre-built PHP versions will be different on Travis CI build.

For example, the `precise` includes the `php-5.3`.

And the `trusty` includes the `php-5.4` to `php-7.3` possibly.

I'm not sure that the internal Travis CI build for PHP versions will be changed and now it's fine for this Travis CI setting at this moment.

Maybe Travis CI will drop the old dist (e.g. precise) in the future.

**Comment by pimjansen** [comment]
@peter279k agree but i dont think we will much longer support those older versions where the builds probably will be executed in isolated docker containers anyways.

5.6 is already EOL and no longer supported so for future versions this will probably be dropped completely

**Comment by peter279k** [comment]
If we drop unsupported PHP versions, we will consider using the `xenial` dist in the future.

**Comment by pimjansen** [comment]
@peter279k well nothing is final actually so i would like to leave that as is for now where the builds run fine.

**Comment by peter279k** [comment]
@pimjansen, thanks for your reply. I think it's time to close this PR until the Travis CI build is failed :).

**Comment by pimjansen** [comment]
@peter279k no worries! Thanks for contributing and thinking with us

**Pull request closed without merging**
