### PR TITLE
Add Restaurant class - A randon Food and Beverage names generate

### PR DESCRIPTION
**Pull request by jzonta**
Add in en_US and pt_BR

### CODE REVIEW

**Comment by fzaninotto** [comment]
Hi, and thanks for your contribution. I suggest you publish these provider as a standalone package instead of contributing to the core. I'll be happy to link to it in Faker's README.

**Comment by jzonta** [comment]
I would like the commit to be accepted, but I followed your advice and created another repository: https://github.com/jzonta/FakerRestaurant

**Comment by fzaninotto** [comment]
Nice! Feel free to open a PR in Faker to add a link to your package in the README.

**Comment by jzonta** [comment]
Seguindo as recomendações, criei o PR para adicionar o link ao README #1374

**Pull request closed without merging**
