### PR TITLE
Enhancement: Echo a greeting

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] echos a greeting using GitHub actions

Related to #1847.

💁‍♂ Let's see if this even works.

### CODE REVIEW

**Comment by localheinz** [comment]
@fzaninotto 

Something is still off - we could expect a workflow to run here, but nothing happens.

**Comment by fzaninotto** [comment]
I know, but the Actions settings seem right...

image

**Comment by localheinz** [comment]
Hmm, weird.

Perhaps we just merge this in, as a test?

We can still remove it afterwards in case this doesn't work at all - less work than merging in #1847 and reverting afterwards.

**Comment by pimjansen** [comment]
Lets indeed merge this as a test

**Pull request merged**
