### PR TITLE
personalIdentityNumber on es_ES Person

### PR DESCRIPTION
**Pull request by mimopo**
Hi! Can we have the personalIdentityNumber method on es_ES Person like in sv_SE Person?

Thanks!

### CODE REVIEW

**Comment by fzaninotto** [comment]
Bump! Could you add a unit test?

**Comment by mimopo** [comment]
Sorry, I had completely forgotten. I'will try to add the unit test asap (may be this weekend).

**Comment by fzaninotto** [comment]
You should add a unit test and a link in the README (in the locale section). I'll close this PR within a few weeks otherwise.

**Comment by fzaninotto** [comment]
Superseded by #763

**Pull request closed without merging**
